arch:
  - ppc64le
  - amd64
language: erlang

os: linux

dist: xenial

before_install:
  - pip install --user cpp-coveralls coveralls-merge

install:
  - rebar get-deps

script: rebar compile xref && rebar skip_deps=true eunit

otp_release:
  - 17.1
  - 19.3
  - 23.0

after_success:
  - cpp-coveralls --exclude lib --exclude tests --gcov-options '\-lp' --dump c.json
  - coveralls-merge c.json erlang.json
